services:
  express-app:
    image: pkrzysiekk/docker-express-app
    ports:
      - 8080:8080
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=5
      - WATCHTOWER_LABEL_ENABLE=true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower